### ISSUE TITLE
VanishNoPacket Fake Join/Quite Message Support

### ISSUE THREAD

**Issue by AaronMcHale** [cnaude/PurpleIRC#103]
With VanishNoPacket join and quit messages can be supressed on join and broadcast to game using commands (/v fakejoin and /v fakequit).

Would it be possible to have support for broadcasting the fake join and fake quit messages into IRC?

### Scenario ###

When someone has the permissions that allow them to join vanished, the join message isn't broadcast into chat, and thus the join message isn't broadcast to IRC (this may or may not be because we are also using MCDocs for join and quit messages).  The vanished player then has to fake join, and when they do, the fake join message is broadcast into game chat, however it isn't broadcast to IRC, thus IRC users never see them joining the server, which I have found can be confusing.

**Comment by cnaude** [comment]
I can do this but it requires a change to the VanishNoPacket code. Are you running this on CraftBukkit or Spigot?

**Comment by AaronMcH** [comment]
Hi, we are running this on Spigot, although it's not a critical feature, just something that would be nice to have, so if it's to much trouble then don't worry about it.

Thanks
Aaron

**Comment by cnaude** [comment]
Added new events to VanishNoPacket: http://h.cnaude.org:8081/job/VanishNoPacket/1/artifact/target/VanishNoPacket.jar
Added fake-join and fake-quit tokens:  http://h.cnaude.org:8081/job/PurpleIRC-spigot/23/artifact/target/PurpleIRC.jar
If you have time please test it. I haven't tested it yet.

**Comment by cnaude** [comment]
I ran a few tests and it seems to work very well.

**Comment by cnaude** [comment]
Have you had a chance to try this yet?

**Comment by AaronMcH** [comment]
Hi sorry for the late reply, was very busy lately, just tested it, do I need to make changes to the config, as I get this error when someone talks in IRC:

[07:11:36 ERROR]: [PurpleIRC] onMessage: null

and it doesn't seem to broadcast the fake join/quit messages.  Using latest builds from your Jenkins server (VNP #5 and PurpleIRC #61).

Thanks
Aaron

**Comment by cnaude** [comment]
Please enable debug mode and try the commands again. Send the log output from that. Please also provide your bot yml and config.yml.
To enable debug mode: /irc debug t
To disable debug mode: /irc debug f
Make sure you bot.yml has fake-join and fake-quit listed in the enabled-message section.

**Comment by AaronMcH** [comment]
Hi enableding the fake-join and fake-quit message types fixed them not sending, thanks.

Here is the debug output for when someone talks

[14:06:57 INFO]: [PurpleIRC] [DEBUG] Message caught <AaronMcH>: test
[14:06:57 INFO]: [PurpleIRC] [DEBUG] Shortify: false
[14:06:57 ERROR]: [PurpleIRC] onMessage: null

Note that I am using the Heorchat message types

Thanks
Aaron
