### ISSUE TITLE
PurpleIRC keeping old displayName after changing name when server is shut down.

### ISSUE THREAD

**Issue by havokoc** [cnaude/PurpleIRC#106]
PurpleIRC keeps an old nick from displayName.cache after I removed the name line from the file while the server was down.
I'm using the latest spigot dev build (# 66).

Scenario:
IRC user Havok changed nick to Havokken once.
IRC user Havokken changed nick back to Havok.
Havok shows up as Havokken ingame when he says "hi".
-Server stop-
-Remove name from displayName.cache-
-Server start-
Havok shows up as Havokken ingame when he says "hi".

**Comment by cnaude** [comment]
Do this:
-Server stop-
-Remove name from displayName.cache-
-Server start-
/irc debug t
-Send test message-
/irc debug
-Pastebin the debug output from the log-

**Comment by havokoc** [comment]
http://pastebin.com/raw.php?i=WFHZi243

**Comment by cnaude** [comment]
The debug shows exactly what I think is happening. The displayName for havok is Havokken. The reason it comes back after you clear the cache is because the game itself still thinks the name is set. What plugin did you use to set that name?

**Comment by havokoc** [comment]
We have disabled all ways of setting a custom nick/name on our server.

**Comment by cnaude** [comment]
If you are not planning on using custom names you can use %NAME% instead of %DISPLAYNAME% in the irc-chat message template. If that is not an option then I have another idea, but it will potentially require you to download a new version of PurpleIRC.

**Comment by havokoc** [comment]
Used that as a solution for now. We were planning on having something with custom nicks, but I'm not sure. Will be in touch if the plans starts getting around again :)
