### ISSUE TITLE
Feature Suggestion: AsyncWorldEdit hook

### ISSUE THREAD

**Issue by austindkelly** [cnaude/PurpleIRC#107]
I was wondering if it is possible to hook to AWE (async world edit- http://www.spigotmc.org/resources/asyncworldedit.327/ ) and have purpleirc spit out logs the same way it does with prism? It would be nice to monitor the queue as its active in irc.

**Comment by cnaude** [comment]
AWE has no events that a plugin can listen for.

**Comment by austindkelly** [comment]
oh sorry misread it as having an API on the wiki didnt read the part about it being on the "todo" list of his. What about WE in general? does that have a way to listen to changes being made and output something to irc?

**Comment by cnaude** [comment]
I had a look at WE source and it too does not have any way for PurpleIRC to catch changes.
