### ISSUE TITLE
Don't relay muted messages (GriefPrevention integration)

### ISSUE THREAD

**Issue by RoboMWM** [cnaude/PurpleIRC#109]
Hi, it appears PurpleIRC relays messages that are already muted by GriefPrevention, which provides many anti-spam capabilities. Is it possible you can integrate with GriefPrevention to avoid relaying muted messages? Thanks in advance.

**Comment by cnaude** [comment]
There is no API in that plugin for me to hook into. I've requested an API for this purpose. http://dev.bukkit.org/bukkit-plugins/grief-prevention/tickets/922-api-is-player-muted-or-metadata/

**Comment by RoboMWM** [comment]
He added the API

**Comment by cnaude** [comment]
Ill check it out.

**Comment by cnaude** [comment]
Please try this: http://h.cnaude.org:8081/job/PurpleIRC-spigot/120/

**Comment by cnaude** [comment]
Latest build of PurpleIRC works great with new GriefPrevention API.
