### ISSUE TITLE
%GROUPSUFFIX% shows player-defined suffix..

### ISSUE THREAD

**Issue by havokoc** [cnaude/PurpleIRC#110]
%GROUPSUFFIX% for IRC->Ingame is showing the player-defined suffix.
This issue does not occur for Ingame->IRC

PurpleIRC Version: 1.0-66
Chat plugin: HeroChat
CONFIG: http://ix.io/jsX
DEBUG: http://paste.i6.io/irizekagip.dos

**Comment by cnaude** [comment]
Can I see the output of "/version PurpleIRC" ?

**Comment by cnaude** [comment]
Also the output from this:
/irc test <playername>

**Comment by havokoc** [comment]
http://paste.i6.io/izeweduwes.sm

**Comment by cnaude** [comment]
Please try latest version: http://h.cnaude.org:8081/job/PurpleIRC-spigot/107/

**Comment by havokoc** [comment]
The issues seems to have been resolved when updating to the latest version. Thanks :)

**Comment by havokoc** [comment]
The issue seems to have come back. Sometimes it shows the formatting like it should, sometimes it shows it like this: http://gyazo.com/e959d23a64b0891a31d304861a93a736 .

New output files.
https://gist.github.com/havokoc/105b60c67c6c206ff3bf

**Comment by havokoc** [comment]
@cnaude *poke*

**Comment by cnaude** [comment]
What part of the screenshot indicates the problem. Is the color missing from suffix?

**Comment by cnaude** [comment]
Please make sure you have the very latest version of Vault installed as well.

**Comment by havokoc** [comment]
![e959d23a64b0891a31d304861a93a736](https://cloud.githubusercontent.com/assets/2565568/9294088/a571a85a-4442-11e5-9d39-2b6c571624e7.png)

I am running Vault version 1.5.3-b37 right now.

**Comment by cnaude** [comment]
When that formatting shows incorrectly is the player offline?

**Comment by havokoc** [comment]
Yes

**Comment by cnaude** [comment]
Please try http://h.cnaude.org:8081/job/PurpleIRC-spigot/126/

**Comment by havokoc** [comment]
That fixed it. Thanks :)
