### ISSUE TITLE
Fix various javadoc failures

### ISSUE THREAD

**Issue by FerusGrim** [cnaude/PurpleIRC#116]
I'm... I'm really not certain how this could happen, but the javadocs are a complete mess.

``` java
/**
 *
 * @author Chris Naude This thread sends player info to linked bots.
 */
public class LinkUpdater {
```

Your name is weird.

``` java
 /**
     *
     * @param plugin
     */
```

What does this do?

``` java
    /**
     *
     */
```

Could you provide a little more info?

And this isn't just all in one class - it's in every class I've looked through, so far.

**Comment by cnaude** [comment]
Yes it is a mess.
