### ISSUE TITLE
Study on OSS maven library incompatiblities and vunerabilities: google-guava

### ISSUE THREAD

**Issue by raux** [cnaude/PurpleIRC#117]
Dear Github OSS Developer,

My name is Raula Kula, a research assistant prof at Osaka University, Japan. Currently I am studying the maintenance of Maven Libraries. I am currently focused on OSS incompatibilites, release management and the varying reasons for library migration.

As a part of my study I particularity focused on the google guava library. https://github.com/google/guava. Particuarly I am interested in the migration to guava library version 18.0. 

We noticed that your project on Github is still configured to depend on a previous incompatible version of fileupload at https://github.com/cnaude/PurpleIRC/blob/master/pom.xml

We understand that there are many reasons for not migrating, thus we be appreciate if you could simply detail the following:

1. Were you aware of this new library and what features it could add to your project?
2. What are some factors that influence you not to update?
3. What would be a key factor that would inspire you to migrate to the next release? 

Also feel free to detail any other information to help us understand your decision. Again, thank you for taking your time off your busy schedule and hope to hear from you soon.

Sincerely,
Raula

**Comment by cnaude** [comment]
1. I was not aware of a new version of guava being available.
2. Usually I only update when I run into problems with the current version or I need a new feature. Sometimes I'll go through my dependencies and check for new versions randomly to keep things up to date.
3. If there is a security issue with the version I am on then I would likely update.

**Comment by raux** [comment]
Thank you for your insights. If no one has anything else to add, you can close this issue. My research is on awareness of migration opportunities so your input will be taken into consideration.
