### ISSUE TITLE
Logging messages sent from IRC to a user in game.

### ISSUE THREAD

**Issue by chibill** [cnaude/PurpleIRC#118]
Is there a way to log the messages sent using .msg from IRC to ingame?

**Comment by cnaude** [comment]
Latest build now has a log-private-chat option. Place this in your bot yml and set it to true.
http://h.cnaude.org:8081/job/PurpleIRC/367/

**Comment by chibill** [comment]
Thanks for the help. :)

**Comment by PabloDons** [comment]
cnaude. It seems the plugin fails to load. gives the following error message:
[PurpleIRC] This plugin is not compatible with Spigot 1.8. Please download the Spigot version from the Spigot site.
any idea why this happens?

**Comment by chibill** [comment]
That's because I did not realize that this did not support spigot.... Can you please also add this to the spigot one?

**Comment by chibill** [comment]
That's because this now that I actually looked is the non spigot version. But the spigot version also has this commit so we just need to wait for a build of that.

**Comment by PabloDons** [comment]
Awesome! Everything seems to work. Thanks cnaude. You have helped us tremendously once again. Your plugin has been a blessing ever since we found it.
