### ISSUE TITLE
Make sure broadcast is sent in sync

### ISSUE THREAD

**Issue by RoboMWM** [cnaude/PurpleIRC#127]
https://gist.github.com/RoboMWM/ba378567150bb8e86895

on Spigot, only the last line appears. `[22:45:27 ERROR]: [PurpleIRC] onMessage: Asynchronous entity track!` This happens when I attempt to send a message after teleporting via a command block.

> [00:54:33] ~md_5: someone on the bukkit wiki seems to thing broadcast is thread safe, it's not

I took a quick look at the code via the stack trace, but didn't see you specifically doing anything async so I'm not sure what's going on...

**Comment by RoboMWM** [comment]
> [01:15:13] RoboMWM: still curious as to why broadcast would also send a message to a commandblock unless there's more to it than that
 [01:30:50] &Thinkofname: it sends to anything that is 'Permissible' and a 'CommandSender'. CommandBlocks match both

**Comment by cnaude** [comment]
If broadcast is not thread safe then I'll just move the broadcast to the main thread.

**Comment by cnaude** [comment]
Please try latest dev build.

**Comment by RoboMWM** [comment]
Seems to be all good now, thanks!
