### ISSUE TITLE
com/dthielke/herochat/ ChannelChatEvent does not exist.

### ISSUE THREAD

**Issue by uncovery** [cnaude/PurpleIRC#130]
[08:23:15] [Server thread/ERROR]: [PurpleIRC] Plugin PurpleIRC v2.1.14-385 has failed to register events for class com.cnaude.purpleirc.GameListeners.HeroChatListener because com/dthielke/herochat/
ChannelChatEvent does not exist.

Using this build of HeroChat: http://dev.bukkit.org/bukkit-plugins/herochat/files/15-herochat-5-7-0/
Using this build of PurpleIRC: http://dev.bukkit.org/bukkit-plugins/purpleirc/files/87-v2-1-14-385/
Running Spigot, Daily 1.9 Builds

Effects: PurpleIRC and Herochat work fine generally, but every /msg chat is being broadcasted on IRC.

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC/393/

**Comment by uncovery** [comment]
Fixed, thanks!
