### ISSUE TITLE
ReportRTS no longer broadcast to IRC, 

### ISSUE THREAD

**Issue by austindkelly** [cnaude/PurpleIRC#132]
I think due to these changes, reportrts is no longer working with PurpleIRC in newer versions than build #29 

http://ci.regularbox.com/job/ReportRTS/29/changes

I seem to still have the correct setting in my bot yaml and configs, but nothing appears when a player fills out a new ticket in the irc channel.

**Comment by cnaude** [comment]
Please try https://h.cnaude.org/jenkins/job/PurpleIRC/395/

**Comment by austindkelly** [comment]
Still no dice. not sure if i have something set wrong:

    - rts-claim
    - rts-complete
    - rts-notify

listed in my bot

  rts-notify: '&r[&aRTS&r] &r[%NAME%&r] &aFilled out ticket #&6%TICKETNUMBER%&a. &b-=-&a
    "&r%MESSAGE%&a" &rHighlight: BOFH c0de slander_u WillRavon Ravon Mrx Mrxx kat

in my config

**Comment by austindkelly** [comment]
ERRORS from console: http://hastebin.com/jabarozoha.avrasm

**Comment by cnaude** [comment]
I was afraid that might happen. Build 396 should handle that exception. https://h.cnaude.org/jenkins/job/PurpleIRC/396/

**Comment by austindkelly** [comment]
working
