### ISSUE TITLE
Multiple messages in MC chat from IRC

### ISSUE THREAD

**Issue by felbane** [cnaude/PurpleIRC#79]
I have noticed an issue that crops up periodically in which messages in IRC which are relayed to Minecraft players show up three times in the minecraft chat log. Messages from Minecraft to IRC are not repeated. This issue has been seen in both 2.1.12 and the latest 2.1.14-121 versions of PurpleIRC.

I have verified that only one bot is listed via `/irc listbots` and have tried to reload the config with `/irc reloadbot minecraft-bot` to no effect.

Pastebins of my configs are found here: [global](http://pastebin.com/xvSwmPSx), [bot](http://pastebin.com/YN7XS1nj)

**Comment by cnaude** [comment]
Is this issue still occurring?
