### ISSUE TITLE
OnTime and output to IRC channels does not show

### ISSUE THREAD

**Issue by austindkelly** [cnaude/PurpleIRC#99]
I can still run ontime commands with `@ontime` for things like `@ontime top` or `@ontime <player>` and previous it would spit out everything just fine to the irc channel, but since upgrading to the latest build tonight, now if i enter a command in irc `@ontime top` it shows up in the console but nothing goes to the irc channel.

I can post screen shots if you need.

**Comment by austindkelly** [comment]
Okay so I am going to try to get the latest versions of this working but im curious what version of Vault, and Protocollib you recommend? I am using the latest version of spigot. I am currently using the latest version of vault and protocol lib, but saw something about reverting to older version in the changelog

**Comment by cnaude** [comment]
Use the very latest versions of Vault (http://dev.bukkit.org/bukkit-plugins/vault/files/49-vault-1-5-2/) and ProtocolLib (http://ci.shadowvolt.com/job/ProtocolLib/).
